#version: '3.8'
#
#services:
#  bot:
#    build: .
#    working_dir: /apps
#    container_name: aiogram_bot
#    environment:
#      TOKEN: postgres
#      DB_HOST: localhost
#      DB_PORT: 5433
#    env_file:
#      - .env
#    command: python main.py
#    depends_on:
#      - pg
#  pg:
#    image: postgres:14.1-alpine
#    restart: always
#    container_name: my_postgres
#    environment:
#      - POSTGRES_PASSWORD=1
#    volumes:
#      - pg_data:/var/lib/postgresql/data/
#    ports:
#      - "5433:5433"
#
#volumes:
#  pg_data:

# docker-compose build   (image)
# docker-compose up      (container)

# docker-compose down
# docker-compose down -v

# dvdrental
#
# docker rm my_postgres
# stop
# remove


#version: "3.8"
#
#services:
#  bot:
#    image: rozievich/mystory_bot:v1.0
#    restart: always
#    working_dir: /apps
#    container_name: story_bot
#    environment:
#      TOKEN: 5935641446:AAFYXxw4IuVwChnDElESEWazcm81nDINSBc
#      DB_HOST: pg
#      DB_PORT: 5432
#      DB_PASS: 1
#    command: python main.py
#    depends_on:
#      - pg
#  pg:
#    image: postgres:14.1-alpine
#    restart: always
#    container_name: my_postgres
#    environment:
#      - POSTGRES_PASSWORD=11
#    volumes:
#      - pg_data:/var/lib/postgresql/data/
#    ports:
#      - "5432:5432"
#volumes:
#  pg_data: